name: Integration test

on:
  push:
    branches:
    - 'master'
    - 'testing'
jobs:
  integration_test:
    runs-on: ubuntu-latest
    container:
      image: python:3.9
      options: --user root
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
    - name: Set up Python
      uses: actions/setup-python@3542bca2639a428e1796aaa6a2ffef0c0f575566 # v3.1.4
      with:
        python-version: '3.x'
    - name: Install Dependencies
      run: |
        apt-get update && apt-get install -y $(cat tests_py/system-requirements.txt)
        pip install -r requirements.txt
        pip install -r tests_py/requirements-dev.txt
    - name: Instal Project
      run: |
        pip3 install ./
    - name: Integration Tests
      run: |
        pytest tests_py/ -v
