name: Integration test

on:
  push:
    branches:
    - 'master'
    - 'testing'
jobs:
  integration_test:
    runs-on: ubuntu-latest
    container:
      image: python:3.9
      options: --user root
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install Dependencies
      run: |
        apt-get update && apt-get install -y $(cat tests_py/system-requirements.txt)
        pip install -r requirements.txt
        pip install -r tests_py/requirements-dev.txt
    - name: Instal Project
      run: |
        pip3 install ./
    - name: Integration Tests
      run: |
        pytest tests_py/ -v
